version: "3.8"
services:
  display-monitor:
    container_name: display-monitor
    image: ghcr.io/belangerpascal/rpi-monior-display:latest 
    volumes:
      - /proc:/proc
      - /lib/modules:/lib/modules
      - /sys:/sys